name: english_speaker
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dart_openai: ^4.1.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.8.3
  http: ^1.1.0
  speech_to_text: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
